source "https://rubygems.org"

# gem "github-pages", "~> 232", group: :jekyll_plugins
gem "jekyll", "~> 4.3"

group :jekyll_plugins do
  gem "jekyll-feed", "~> 0.13"
  gem 'jekyll-sitemap', '~> 1.4'
  gem 'jekyll-compose', '~> 0.12.0'
  gem 'jekyll-postfiles', '~> 3.1'
  gem 'jekyll-spaceship'
  gem 'ostruct'
end

# Windows and JRuby does not include zoneinfo files, so bundle the tzinfo-data gem
# and associated library.
platforms :windows, :jruby do
  gem "tzinfo", ">= 1", "< 3"
  gem "tzinfo-data"
  gem "wdm", "~> 0.1"
  gem "http_parser.rb", "~> 0.6.0"
  gem "webrick", "~> 1.7"
end
